" theme
  color desert
  set background=dark

" options
set hlsearch
set showmatch
set ignorecase
set tabstop=4
set shell=/bin/bash


" syntax highlight
  syntax on
  filetype on
  au BufNewFile,BufRead *.cmp set filetype=xml
  au BufNewFile,BufRead *.app set filetype=xml

" vundle stuffs
  set nocompatible              " be iMproved, required
  filetype off                  " required

  " set the runtime path to include Vundle and initialize
  set rtp+=~/.vim/bundle/Vundle.vim
  call vundle#begin()

  Plugin 'VundleVim/Vundle.vim'

  " The following are examples of different formats supported.
  Plugin 'airblade/vim-gitgutter'
  Plugin 'dracula/vim'

  " All of your Plugins must be added before the following line
  call vundle#end()            " required
  
  filetype on
